name: Update Fantasy Data

on:
  schedule:
    - cron: "0 11 * * 2" # 6:00 AM EST (11:00 UTC)
  workflow_dispatch:

permissions:
  contents: write  # needed for push + deploy

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch ESPN API and save response
        env:
          ESPN_SWID: ${{ secrets.ESPN_SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
        run: |
          set -o errexit -o pipefail
          curl -s \
            -X GET "https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2025/segments/0/leagues/1085647814?view=mBoxscore&view=mTeam" \
            -H "Accept: application/json" \
            -H "Cookie: SWID=$ESPN_SWID; espn_s2={$ESPN_S2}" \
            | jq '{schedule, teams, scoringPeriodId}' > src/helpers/league-data.json
          jq type src/helpers/league-data.json >/dev/null

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/helpers/league-data.json
          git commit -m "Update ESPN API response [skip ci]" || echo "No changes"
          git push

  deploy:
    needs: fetch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci --ignore-scripts
      - run: npm run build -- --chunkSizeWarningLimit=1000

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d dist -u "github-actions-bot <github-actions[bot]@users.noreply.github.com>" -r "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
